tasks:
  - name: aws-cli-terraform
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace

      # Install AWS CLI
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -rf awscliv2.zip aws

      # Install Terraform
      sudo apt-get update
      sudo apt-get install -y unzip
      curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
      unzip /tmp/terraform.zip -d /tmp
      sudo mv /tmp/terraform /usr/local/bin/
      rm /tmp/terraform.zip

      cd $THEIA_WORKSPACE_ROOT